Repository submariner-io/releases, pull requests merged in 2021-05, with the labels that each got.

#140 Add CII badge, remove PR-triggered badges
  README.md
Labels: cncf, documentation

#142 Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cncf, documentation, ready-to-test

#143 Shipyard phase for v0.10.0-m1
  releases/v0.10.0-m1.yaml
Labels: ready-to-test
