Repository submariner-io/releases, pull requests merged in 2022-10, with the labels that each got.

#508 Initiating release of 0.14.0-m2
  releases/v0.14.0-m2.yaml
Labels: automated

#509 Advancing 0.14.0-m2 release to status: admiral
  releases/v0.14.0-m2.yaml
Labels: automated

#510 Advancing 0.14.0-m2 release to status: projects
  releases/v0.14.0-m2.yaml
Labels: automated

#511 Advancing 0.14.0-m2 release to status: installers
  releases/v0.14.0-m2.yaml
Labels: automated

#512 Advancing 0.14.0-m2 release to status: released
  releases/v0.14.0-m2.yaml
Labels: automated

#515 Add issues:write permission to broken links GHA, only run on main repo
  .github/workflows/periodic.yml
Labels: automation

#516 Initiating release of 0.14.0-rc0
  releases/v0.14.0-rc0.yaml
Labels: automated

#528 Advancing 0.14.0-rc0 release to status: shipyard
  releases/v0.14.0-rc0.yaml
Labels: automated

#529 Advancing 0.14.0-rc0 release to status: admiral
  releases/v0.14.0-rc0.yaml
Labels: automated

#530 Advancing 0.14.0-rc0 release to status: projects
  releases/v0.14.0-rc0.yaml
Labels: automated

#531 Advancing 0.14.0-rc0 release to status: installers
  releases/v0.14.0-rc0.yaml
Labels: automated

#533 Advancing 0.14.0-rc1 release to status: admiral
  releases/v0.14.0-rc1.yaml
Labels: automated

#534 Advancing 0.14.0-rc1 release to status: projects
  releases/v0.14.0-rc1.yaml
Labels: automated

#535 Advancing 0.14.0-rc1 release to status: installers
  releases/v0.14.0-rc1.yaml
Labels: ready-to-test, automated

#536 Advancing 0.14.0-rc1 release to status: released
  releases/v0.14.0-rc1.yaml
Labels: automated
