Repository submariner-io/releases, pull requests merged in 2022-09, with the labels that each got.

#474 Initiating release of 0.14.0-m1
  releases/v0.14.0-m1.yaml
Labels: automated

#482 Advancing 0.14.0-m1 release to status: admiral
  releases/v0.14.0-m1.yaml
Labels: automated

#484 Advancing 0.14.0-m1 release to status: projects
  releases/v0.14.0-m1.yaml
Labels: automated

#485 Advancing 0.14.0-m1 release to status: installers
  releases/v0.14.0-m1.yaml
Labels: automated

#486 Advancing 0.14.0-m1 release to status: released
  releases/v0.14.0-m1.yaml
Labels: automated

#497 Use base branch for the dapper Dockerfile
  Dockerfile.dapper
Labels: backport, maintenance

#501 Add repository-projects:read to release job token
  .github/workflows/release.yml
Labels: bug

#503 Advancing 0.13.1 release to status: installers
  releases/v0.13.1.yaml
Labels: automated

#504 Advancing 0.13.1 release to status: released
  releases/v0.13.1.yaml
Labels: automated
