Repository submariner-io/releases, pull requests merged in 2023-07, with the labels that each got.

#775 Initiating release of 0.15.2
  releases/v0.15.2.yaml
Labels: automated

#776 Advancing 0.15.2 release to status: admiral
  releases/v0.15.2.yaml
Labels: automated

#777 Advancing 0.15.2 release to status: projects
  releases/v0.15.2.yaml
Labels: automated

#778 Advancing 0.15.2 release to status: installers
  releases/v0.15.2.yaml
Labels: automated

#779 Advancing 0.15.2 release to status: released
  releases/v0.15.2.yaml
Labels: ready-to-test, automated

#780 Initiating release of 0.14.6
  releases/v0.14.6.yaml
Labels: automated

#783 Advancing 0.14.6 release to status: admiral
  releases/v0.14.6.yaml
Labels: automated

#784 Advancing 0.14.6 release to status: projects
  releases/v0.14.6.yaml
Labels: automated

#785 Advancing 0.14.6 release to status: installers
  releases/v0.14.6.yaml
Labels: automated

#786 Advancing 0.14.6 release to status: released
  releases/v0.14.6.yaml
Labels: automated

#771 Automated backport of #767: Split the “Components:” header off
  scripts/release.sh
Labels: automated-backport

#789 Advancing 0.16.0-m2 release to status: admiral
  releases/v0.16.0-m2.yaml
Labels: automated

#791 Advancing 0.16.0-m2 release to status: installers
  releases/v0.16.0-m2.yaml
Labels: automated

#792 Advancing 0.16.0-m2 release to status: released
  releases/v0.16.0-m2.yaml
Labels: automated
