Repository submariner-io/releases, pull requests merged in 2023-06, with the labels that each got.

#740 Advancing 0.16.0-m0 release to status: projects
  releases/v0.16.0-m0.yaml
Labels: automated

#742 Advancing 0.16.0-m0 release to status: installers
  releases/v0.16.0-m0.yaml
Labels: automated

#743 Advancing 0.16.0-m0 release to status: released
  releases/v0.16.0-m0.yaml
Labels: automated

#745 Initiating release of 0.14.5
  releases/v0.14.5.yaml
Labels: automated

#746 Advancing 0.14.5 release to status: admiral
  releases/v0.14.5.yaml
Labels: automated

#747 Advancing 0.14.5 release to status: projects
  releases/v0.14.5.yaml
Labels: automated

#748 Advancing 0.14.5 release to status: installers
  releases/v0.14.5.yaml
Labels: automated

#749 Advancing 0.14.5 release to status: released
  releases/v0.14.5.yaml
Labels: automated

#751 Initiating release of 0.15.1
  releases/v0.15.1.yaml
Labels: automated

#753 Advancing 0.15.1 release to status: projects
  releases/v0.15.1.yaml
Labels: automated

#754 Advancing 0.15.1 release to status: installers
  releases/v0.15.1.yaml
Labels: automated

#755 Advancing 0.15.1 release to status: released
  releases/v0.15.1.yaml
Labels: automated

#757 Initiating release of 0.13.6
  releases/v0.13.6.yaml
Labels: automated

#758 Advancing 0.13.6 release to status: admiral
  releases/v0.13.6.yaml
Labels: automated

#759 Advancing 0.13.6 release to status: projects
  releases/v0.13.6.yaml
Labels: automated

#765 Advancing 0.16.0-m1 release to status: admiral
  releases/v0.16.0-m1.yaml
Labels: automated

#766 Advancing 0.16.0-m1 release to status: projects
  releases/v0.16.0-m1.yaml
Labels: automated

#767 Split the “Components:” header off
  scripts/release.sh
Labels: backport

#768 Advancing 0.16.0-m1 release to status: installers
  releases/v0.16.0-m1.yaml
Labels: automated

#769 Advancing 0.16.0-m1 release to status: released
  releases/v0.16.0-m1.yaml
Labels: automated

#764 Automated backport of #715: List components in release PRs
  scripts/release.sh
Labels: automated-backport
